"""init schema: utilisateurs, roles, offres, candidatures

Revision ID: db3452db8542
Revises: 95d830991948
Create Date: 2026-07-21 13:01:34.702390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3452db8542'
down_revision: Union[str, Sequence[str], None] = '95d830991948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_utilisateurs_username'), 'utilisateurs', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateurs_username'), table_name='utilisateurs')
    op.drop_column('utilisateurs', 'username')
    # ### end Alembic commands ###
